### PR TITLE
Use native big integers

### PR DESCRIPTION
**Pull request by bclement-ocp**
**Note**: I am opening this PR as a discussion — we have been using this version of the stubs in internal projects at OCamlPro for the past couple of months, and believe it can be useful to others that care about the web worker use case. We'd like to ideally contribute it back to the original stubs, but understand that it is a big change and others may care more about supporting legacy platforms, so happy to hear any thoughts. If preferable, we are open to publishing the "native bigint" version as a separate package, although we'd prefer to avoid such fragmentation.

The primitive BigInt type is one of the types supported by the structured clone algorithm; however, while biginteger.js already falls back to the native BigInt type when available, it does so by wrapping native BigInt values into its own class. This makes it incompatible with the structured clone algorithm, and currently prevents Z.t values from being shared across execution contexts (e.g. web workers).

This patch rewrites most of zarith_stubs_js to remove the biginteger.js library and directly use the native BigInt type, making it possible to share Z.t values across execution contexts without marshalling.

The downside is that the library now requires an execution environment that supports the primitive BigInt type. This includes all major browsers released after 2020 and all node.js versions released after 2018.

### CODE REVIEW

**Comment by TyOverby** [comment]
Thanks for the pull request!

I've finished an audit of our internal systems to make sure that we don't run jsoo output on any javascript runtimes that are missing the primitive BigInt type, and am relieved to find that we don't have any, so I'm happy to avoid the fragmentation and merge this PR. 

I started the process of importing these changes, and found a few classes of bugs that caused tests to fail.  I'm going to try to open-source our test suite so that you can run it, but here's a summary of the failures that I noticed.

## Missing `let` in `ml_z_bin`

When you changed `var` to `let`, the `ml_z_bin` function broke due to scoping.

Here's a fix:

```diff
  //Provides: ml_z_bin
  //Requires: ml_z_normalize, caml_invalid_argument
  function ml_z_bin(n, k) {
    if (k < 0) caml_invalid_argument("Z.bin: non-positive argument");
    n = BigInt(n);
    k = BigInt(k);
    let coeff = 1n;
    for (let x = n - k + 1n; x <= n; x++) coeff *= x;
-   for (x = 1n; x <= k; x++) coeff /= x;
+   for (let x = 1n; x <= k; x++) coeff /= x;
    return ml_z_normalize(coeff);
  }
```

## `ml_z_next_prime` produces different results

The docs for `nextprime` say this:

```
external nextprime: t -> t = "ml_z_nextprime"
(** Returns the next prime greater than the argument.
    The result is only prime with very high probability. *)
```

Because it uses a probablistic prime finder which involves randomness, I wouldn't be surprised to see a few results differ, but the function in this PR appears to have a behavior identical to the identity function.  e.g. `next_prime 12 = 12`

## Marshalling fails for some numbers

I spent a few hours trying to figure out why these failed, but didn't get anywhere.  It looks like the WeakMap in question comes from js_of_ocaml's mashalling stubs.

```diff
diff --git a/lib/zarith_stubs_js/test/of_string_to_string.ml b/lib/zarith_stubs_js/test/of_string_to_string.ml
--- a/lib/zarith_stubs_js/test/of_string_to_string.ml
+++ b/lib/zarith_stubs_js/test/of_string_to_string.ml
@@ -217,39 +207,12 @@ module Marshal = struct
 
   let%expect_test "marshal large" =
     m "8432103214690897934401335661952849215774309719238";
-    [%expect
-      {|
-        84,95,A6,BE,00,00,00,2D
-        00,00,00,01,00,00,00,09
-        00,00,00,06,18,5F,7A,00
-        00,00,00,1C,00,00,00,00
-        00,00,00,20,00,00,00,00
-        18,C6,9C,63,3B,6A,F2,2A
-        E0,41,A2,BE,0F,2B,5F,8B
-        0C,CC,95,FC,C4,05,00,00
-        00 |}];
+    [%expect.unreachable];
     m "-107549090292258971570605440155";
-    [%expect
-      {|
-        84,95,A6,BE,00,00,00,25
-        00,00,00,01,00,00,00,07
-        00,00,00,05,18,5F,7A,00
-        00,00,00,14,00,00,00,00
-        00,00,00,18,01,00,00,00
-        10,9B,BC,2C,E8,CF,9C,72
-        2F,BB,85,82,5B,01,00,00
-        00 |}];
+    [%expect.unreachable];
     m "107549090292258971570605440155";
-    [%expect
-      {|
-        84,95,A6,BE,00,00,00,25
-        00,00,00,01,00,00,00,07
-        00,00,00,05,18,5F,7A,00
-        00,00,00,14,00,00,00,00
-        00,00,00,18,00,00,00,00
-        10,9B,BC,2C,E8,CF,9C,72
-        2F,BB,85,82,5B,01,00,00
-        00 |}]
+    [%expect.unreachable]
+  [@@expect.uncaught_exn {| (Failure "TypeError: Invalid value used as weak map key") |}]
   ;;
 
   let%expect_test ("marshal mix len" [@tags "64-bits-only"]) =
@@ -281,15 +244,8 @@ module Marshal = struct
 
   let%expect_test ("marshal mix len" [@tags "js-only"]) =
     m "-549389047489539543158";
-    [%expect
-      {|
-        84,95,A6,BE,00,00,00,21
-        00,00,00,01,00,00,00,06
-        00,00,00,05,18,5F,7A,00
-        00,00,00,10,00,00,00,00
-        00,00,00,18,01,00,00,00
-        0C,76,10,37,60,E7,FB,4D
-        C8,1D,00,00,00 |}]
+    [%expect.unreachable]
+  [@@expect.uncaught_exn {| (Failure "TypeError: Invalid value used as weak map key") |}]
   ;;
 end
```

## `hamdist` weirdness changed

The C stubs for zarith have inconsistent behavior for the `hamdist` function.  If both args fit in an int, then it's fine if both are negative.  When at least one of them is a GMP int, then it throws a "negative arguments" exception, even if both are negative.

We previously had code that replicated this, which you remove in this PR.  Here's a patch that adds it back

```diiff
  function ml_z_hamdist(z1, z2) {
    if ((z1 < 0) !== (z2 < 0)) {
      caml_raise_constant(caml_named_value("ml_z_overflow"));
    }
-   if (z1 < 0 || z2 < 0) {
+   if((typeof z1 === 'bignum' || typeof z2 === 'bignum') && (z1 < 0 || z2 < 0 )) {
      caml_invalid_argument("Z.hamdist: negative arguments");
    }
  
    return ml_z_popcount(BigInt(z1) ^ BigInt(z2));
  }
```

**Comment by bclement-ocp** [comment]
Thank you for looking into this, and happy if we can avoid the fragmentation as well!

I admit I had a bit of trouble finding appropriate tests, and forgot to mention that on the PR — I ran the Zarith test suite and a couple tests for the functions we use internally but we don't use some of the more "obscure" ones, so you running these internal tests is useful :)

I will apply the fixes you identified (sorry for the `let` one, changing `var` to `let` was an afterthought and not as thoroughly checked — maybe I should revert to the version without `let`?) and take a look at the `ml_z_next_prime` and WeakMap issues.

**Comment by bclement-ocp** [comment]
I have pushed the fixes you identified, as well as a fix for `ml_z_nextprime` (there was a 1 character typo, and I also mixed up the iteration order on digits when generating large random number by trying to be too clever).

I have looked at the numbers for which marshalling fails in your test, but all these tests seem to pass on my machine, using node v20.9.0 and js_of_ocaml 5.4.0. Would you mind sharing more information on your test environment?

I can't try to reproduce on these versions right now, but this looks like a js_of_ocaml bug that was probably introduced by ocsigen/js_of_ocaml#814 (version 3.5.0) and fixed in ocsigen/js_of_ocaml#1457 (version 5.2.0).

**Comment by TyOverby** [comment]
> this looks like a js_of_ocaml bug that was probably introduced by https://github.com/ocsigen/js_of_ocaml/pull/814 (version 3.5.0) and fixed in https://github.com/ocsigen/js_of_ocaml/pull/1457 (version 5.2.0).

Ooh good find.  We were missing that fix and now marshalling works.

**Comment by TyOverby** [comment]
I've pulled in your updated changes and everything passes :tada: 

The changes are going through code-review internally, and I expect the changes to make their way back to Github in a week or two

**Comment by TyOverby** [comment]
:tada:

**Comment by TyOverby** [comment]
this change will be in our next release to Opam

**Comment by hhugo** [comment]
The readme still mentions
> [Zarith Stubs JS](https://github.com/janestreet/zarith_stubs_js) is a reimplementation of the native C functions in JavaScript. It makes extensive use of [peterolson/BigInteger.js](https://github.com/peterolson/BigInteger.js) as a shim for browser BigInt functionality and also for the implementations of many numerical algorithms.

**Pull request merged**
